Linear Regression -the simplest linear model


```{r}
require(UsingR)
require(ggplot2)
head(father.son)
ggplot(father.son,aes(x=fheight,y=sheight))+geom_point()+geom_smooth(method="lm")+labs(x="Fathers",y="Sons")
heightsLM<-lm(sheight~fheight,data=father.son)
heightsLM
summary(heightsLM)
```

ANOVA

```{r}
data(tips,package="reshape2")
head(tips)
tipsAnova<-aov(tip~day-1,data=tips)
tipsLM<-lm(tip~day-1,data=tips)
summary(tipsAnova)
summary(tipsLM)
require(plyr)
tipsByDay<-ddply(tips,"day",summarize,tip.mean=mean(tip),tip.sd=sd(tip),Length=NROW(tip),tfrac=qt(p=0.9,df=Length-1),Lower=tip.mean-tfrac*tip.sd/sqrt(Length),Upper=tip.mean+tfrac*tip.sd/sqrt(Length))
#Then you do not have to use 
#ddply (.data=tips,variables="day",function,)
tipsInfo<-summary(tipsLM)
tipsCoef<-as.data.frame(tipsInfo$coefficients[,1:2])
tipsCoef<-within(tipsCoef,{Lower<-Estimate-qt(p=0.9,df=tipsInfo$df[2])* `Std. Error`
                           Upper<-Estimate+qt(p=0.9,df=tipsInfo$df[2])* `Std. Error`
                           day<-rownames(tipsCoef)
                           })
#Evaluate an R expression in an environment constructed from data, possibly modifying the original data. so you do not need to make a vector and then use cbind
ggplot(tipsByDay,aes(x=tip.mean,y=day))+geom_point()+geom_errorbarh(aes(xmin=Lower,xmax=Upper),height=.3)+ggtitle("Tips by day Calculated manually")

ggplot(tipsCoef,aes(x=Estimate,y=day))+geom_point()+geom_errorbarh(aes(xmin=Lower,xmax=Upper),height=.3)+ggtitle("Tips by day calciulated from regression model")

housing<-read.table("http://www.jaredlander.com/data/housing.csv",sep=",",header=TRUE,stringsAsFactors=FALSE)

names(housing)<-c("Neighborhood","Class","Units","YearBuilt","SqFt","Income","IncomePerSqFt","Expense","ExpernsePerSqFt","NetIncome","Value","ValuePerSqFt","Boro")
head(housing)
#histgram
ggplot(housing,aes(x=ValuePerSqFt))+geom_histogram(binwidth=10)+labs(x="Value per Square Foot")

ggplot(housing,aes(x=ValuePerSqFt,fill=Boro))+geom_histogram(binwidth=10)+labs(x="Value per Square Foot")

ggplot(housing,aes(x=ValuePerSqFt,fill=Boro))+geom_histogram(binwidth=10)+labs(x="Value per Square Foot")+facet_wrap(~Boro)

ggplot(housing,aes(x=SqFt))+geom_histogram()
ggplot(housing,aes(x=Units))+geom_histogram()
ggplot(housing[housing$Units<1000,],aes(x=SqFt))+geom_histogram()
ggplot(housing[housing$Units<1000,],aes(x=Units))+geom_histogram()
ggplot(housing,aes(x=SqFt,y=ValuePerSqFt))+geom_point()
ggplot(housing,aes(x=Units,y=ValuePerSqFt))+geom_point()
ggplot(housing[housing$Units<1000,],aes(x=Units,y=ValuePerSqFt))+geom_point()
ggplot(housing[housing$Units<1000,],aes(x=Units,y=ValuePerSqFt))+geom_point()
sum(housing$Units>=1000)
housing<-housing[housing$Units<1000,]
ggplot(housing,aes(x=SqFt,y=ValuePerSqFt))+geom_point()
ggplot(housing,aes(x=log(SqFt),y=ValuePerSqFt))+geom_point()
ggplot(housing,aes(x=SqFt,y=log(ValuePerSqFt)))+geom_point()
ggplot(housing,aes(x=log(SqFt),y=log(ValuePerSqFt)))+geom_point()
house1<-lm(ValuePerSqFt~Units+SqFt+Boro,data=housing)
summary(house1)
house1$coefficients
#install.packages("coefplot")
require(coefplot)
coefplot(house1)
house2<-lm(ValuePerSqFt~Units*SqFt+Boro,data=housing)
house3<-lm(ValuePerSqFt~Units:SqFt+Boro,data=housing)
house2$coefficients
house3$coefficients
coefplot(house2)
coefplot(house3)
house4<-lm(ValuePerSqFt~SqFt*Units*Income,housing)
house4$coefficients
house5<-lm(ValuePerSqFt~Class*Boro,housing)
house5$coefficients
house6<-lm(ValuePerSqFt~I(SqFt/Units)+Boro,housing)
#INCLUDE IN R
house7<-lm(ValuePerSqFt~(Units+SqFt)^2,housing)
house8<-lm(ValuePerSqFt~Units*SqFt,housing)
house9<-lm(ValuePerSqFt~I(Units+SqFt)^2,housing)
identical(house7$coefficients,house8$coefficients)
multiplot(house1,house2,house3)
#make prediction
housingNew<-read.table("http://www.jaredlander.com/data/housingNew.csv",sep=",",header=TRUE,stringsAsFactors=FALSE)
housePredict<-predict(house2,newdata=housingNew,se.fit=TRUE,interval="prediction",level=.95)
head(housePredict$fit)
head(housePredict$se.fit)
```